apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db
  labels:
    app: nextcloud-db
  namespace: nextcloud
spec:
  selector:
    pod-label: nextcloud-db-pod
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
