apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-db-pv
  namespace: nextcloud
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /media/Linux/pv/nextcloud/
    server: 192.168.1.31

