apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-db-pvc
  labels:
    app: nextcloud-db
  namespace: nextcloud
spec:
  storageClassName: ""
  volumeName: nextcloud-db-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
