apiVersion: v1
kind: Service
metadata:
  name: mobsf-web
  namespace: mobsf
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 30080
      targetPort: 8000
  selector:
    app: mobsf
