apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-test
spec:
  storageClassName: managed-nfs-storage 
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 50Mi
