apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  labels:
    app: nextcloud-server
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
