apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transmission               # < label for tagging and reference
  name: transmission                # < name of the deployment
  namespace: transmission           # < namespace where to place the deployment and pods               # < namespace where place the deployment and pods
spec:
  replicas: 1                     # < number of pods to deploy
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: transmission
  strategy:
    rollingUpdate:
      maxSurge: 0                 # < The number of pods that can be created above the desired amount of pods during an update
      maxUnavailable: 1           # < The number of pods that can be unavailable during the update process
    type: RollingUpdate           # < New pods are added gradually, and old pods are terminated gradually
  template:
    metadata:
      labels:
        app: transmission
    spec:
      volumes:
      - name: transmission-config     # < linkname of the volume for the pvc
        persistentVolumeClaim:
          claimName: transmission-pvc-config  # < pvc name we created in the previous yaml
      - name: transmission-watch
        persistentVolumeClaim:
          claimName: transmission-pvc-watch
      - name: transmission-download
        persistentVolumeClaim:
          claimName: transmission-pvc-download
      containers:
      - env:                       # < environment variables. See https://hub.docker.com/r/linuxserver/plex
        - name: PGID
          value: "\x31\x30\x30\x31"    # < ASCII code for '1001'
        - name: PUID
          value: "\x31\x30\x30\x31" # < ACII code for '1035'
        - name: TZ
          value: Asia/Dubai  # < Timezone
        image:    # < the name of the docker image we will use
        imagePullPolicy: Always    # < always use the latest image when creating container/pod
        name: plexserver           # < name of container
        ports:
        - containerPort: 9091     # < required network portnumber. See https://hub.docker.com/r/linuxserver/plex
          name: web            # < reference name from the port in the service yaml
          protocol: TCP
        - containerPort: 51413
          name: transmission-tcp
          protocol: TCP
        - containerPort: 51413
          name: transmission-udp
          protocol: UDP
        resources: {}
        stdin: true
        tty: true
        volumeMounts:            # < the volume mount in the container. Look at the relation volumelabel->pvc->pv
        - mountPath: /config     # < mount location in the container
          name: nfs-plex-config  # < volumelabel configured earlier in the yaml file
        - mountPath: /data
          name: nfs-data 
      restartPolicy: Always
