kind: Service
apiVersion: v1
metadata:
  name: transmission-tcp
  namespace: transmission
  annotations:
    metallb.universe.tf/allow-shared-ip: transmission
spec:
  selector:
    app: transmission
  ports:                      
  - port: 9091               
    targetPort: 9091        
    name: web
    protocol: TCP
  - port: 51413
    targetPort: 51413
    name: tran-tcp
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.1.31

