kind: Service
apiVersion: v1
metadata:
  name: transmission-tcp
  namespace: transmission
spec:
  selector:
    app: transmission
  ports:                      
  - port: 9091               
    targetPort: 9091        
    name: web
    protocol: TCP
    nodePort: 30008
  - port: 51413
    targetPort: 51413
    name: tran-tcp
    protocol: TCP
    nodePort: 30009
  type: NodePort

