apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: apps
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      nodePort: 30004
      targetPort: 6379
  selector:
    app: redis
