apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
  namespace: apps
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.0.7-alpine
          ports:
          - containerPort: 6379
